framework:
    rate_limiter:
        login_attempts:
            policy: 'sliding_window'
            limit: 5
            interval: '15 minutes'
        register_attempts:
            policy: 'sliding_window'
            limit: 5
            interval: '1 hour'
        contact_attempts:
            policy: 'sliding_window'
            limit: 5
            interval: '1 hour'
        profile_update_attempts:
            policy: 'sliding_window'
            limit: 10
            interval: '15 minutes'
